### ISSUE TITLE
Not seeing the dropdown to select the extension on the "Extensions/Readme Files" tab.

### ISSUE THREAD

**Issue by FilkerZero** [light-and-ray/sd-webui-readme-browser#5]
After installing the extension in the Automatic1111 webui, I do see the "Readme Files" subtab under the "Extensions" tab, the settings appear and match what's in the Readme.md for the extension, but the tab is empty.
<img width="836" alt="image" src="https://github.com/light-and-ray/sd-webui-readme-browser/assets/42746731/6863c83a-4d42-42d9-a26c-b02c7a110ef0">

I'm using the Opera browser on Windows 11 Professional and the most recent webui (as of a few weeks ago).

Is there some step I need to perform to get the extension selection dropdown  to appear?

*UPDATE:*

I updated the extensions again and restarted Automatic1111 webui again, and I now see the following in the Automatic1111 console window:

<img width="863" alt="image" src="https://github.com/light-and-ray/sd-webui-readme-browser/assets/42746731/e75acf49-47ad-43a6-9f61-9b8af83d96c2">

I don't know if this was showing up prior to updating the extensions, but I suspect it was.

The last line of the error dump says it can't find the path `...\\extensions\sd-webui-readme-browser\\wiki` - Is this something that I need to create?

**Comment by FilkerZero** [comment]
Manually creating the `wiki` directory in the extension folder (see path in the error dump in the post above) seems to have fixed the issue.  This is a workaround; perhaps the directory should be created automatically by the extension initialization script if it's not found.

**Comment by light-and-ray** [comment]
Thanks for reporting
